### ISSUE TITLE
Trouble opening files, says corrupt/unopenable?

### ISSUE THREAD

**Issue by jesswhyte** [ghalfacree/Physical-Objects#1]
Hi, great project, I'd love to try to make it. I'm having trouble opening the files though, just wanted to check in and see if it's me or the actual files? Would you be able to re-upload? Thank you

**Comment by ghalfacree** [comment]
Hi, Jess.

Which file is showing as corrupt? I've tried opening them all myself - using LibreOffice Draw for the CDRs, LibreCAD for the DXF, Evince for the PDFs and the Gnome Image Viewer for the PNG, JPG, and SVG, and they all open perfectly - not one gave any error.

-Gareth

**Comment by jesswhyte** [comment]
Hi, thank you for checking. So, the DXF opened fine at home for me on
LibreCAD.

I must not have imported them correctly with AutoCAD at school (where I
first tried to open the files)

**Comment by ghalfacree** [comment]
Glad to hear you got it working!

**Comment by jesswhyte** [comment]
Gareth,

Check it out (pics attached). Thanks for the plans, they were great.

Thanks,

Jess
